"""Add Freebie model

Revision ID: e9182cf24a3d
Revises: 70310d00359c
Create Date: 2023-12-11 09:17:47.862814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9182cf24a3d'
down_revision = '70310d00359c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
